# Image Python officielle légère
FROM python:3.12-slim-bookworm

# Evite les fichiers .pyc
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Dossier de travail dans le container
WORKDIR /app

# Copier requirements
COPY requirements.txt .

# Installer dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le projet
COPY . .

# Exposer le port 8000
EXPOSE 8000

# Commande de lancement
CMD ["uvicorn", "code.app:app", "--host", "0.0.0.0", "--port", "8000"]